import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../View/Navbar/index'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
      <body className={`${inter.className} max-w-screen-xl mx-auto px-4`}>{children}</body>
      </div>
    </html>
  );
}
